export const ALERT_FETCH_USER_ERROR = 'ALERT_FETCH_USER_ERROR'
export const ALERT_FETCH_POST_ERROR  = 'ALERT_FETCH_POST_ERROR'
export const ALERT_FETCH_LOCATION_ERROR  = 'ALERT_FETCH_LOCATION_ERROR'
export const ERROR_LOAD_DASHBOARD  = 'FETCH_POST_ERROR'
