export const CREATE_NEW_POST_PENDING = 'CREATE_NEW_POST_PENDING'  
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS'
export const CREATE_NEW_POST_ERROR = 'CREATE_NEW_POST_ERROR'

export const REQUEST_HANGOUT_PENDING = 'REQUEST_HANGOUT_PENDING'
export const REQUEST_HANGOUT_SUCCESS = 'REQUEST_HANGOUT_SUCCESS'
export const REQUEST_HANGOUT_ERROR = 'REQUEST_HANGOUT_ERROR'

export const ACCEPT_HANGOUT_PENDING = 'ACCEPT_HANGOUT_PENDING'
export const ACCEPT_HANGOUT_SUCCESS = 'ACCEPT_HANGOUT_SUCCESS'
export const ACCEPT_HANGOUT_ERROR = 'ACCEPT_HANGOUT_ERROR'