export const FETCH_ALL_USERS_PENDING  = 'FETCH_ALL_USERS_PENDING'
export const FETCH_ALL_USERS_SUCCESS  = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_ERROR    = 'FETCH_ALL_USERS_ERROR'

export const FETCH_CITY_USERS_PENDING = 'FETCH_CITY_USERS_PENDING'
export const FETCH_CITY_USERS_SUCCESS = 'FETCH_CITY_USERS_SUCCESS'
export const FETCH_CITY_USERS_ERROR   = 'FETCH_CITY_USERS_ERROR'

export const FETCH_USER_PENDING       = 'FETCH_USER_PENDING'
export const FETCH_USER_SUCCESS       = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR         = 'FETCH_USER_ERROR'

export const FETCH_USERS_LOCATION_PENDING = 'FETCH_USERS_LOCATION_PENDING'
export const FETCH_USERS_LOCATION_SUCCESS = 'FETCH_USERS_LOCATION_SUCCESS'
export const FETCH_USERS_LOCATION_ERROR = 'FETCH_USERS_LOCATION_ERROR'
